// ==========================================
// M2 Health Engine V1.6 FINAL
// 振宇 FCN 系統｜持倉健檢引擎
// ==========================================

const M2_EARLY_EXIT_STATE_KEY = "m2_early_exit_state_v1";
const M2_KNOCKIN_STATE_KEY = "m2_knockin_state_v1";

function toNumber(v, fallback = 0) { const n = Number(v); return Number.isFinite(n) ? n : fallback; }
function round(v, digits = 2) { const factor = 10 ** digits; return Math.round(toNumber(v) * factor) / factor; }
function diffDays(startStr, endDate = new Date()) { if (!startStr) return 0; const start = new Date(startStr); if (Number.isNaN(start.getTime())) return 0; return Math.max(0, Math.floor((endDate.getTime()-start.getTime())/(1000*60*60*24))); }
function fullMonthsHeld(entryTime) { return Math.floor(diffDays(entryTime)/30); }
function getDecisionSignal(snapshotBalancePct,endNetPct,stockHealth){if(endNetPct < -15 || (stockHealth === "danger" && snapshotBalancePct < -20)) return {signal:"red",label:"🔴 優先處理",note:"到期淨損失偏大，或已跌破 KI 且 Snapshot 壓力過高"};if(endNetPct < 0 || snapshotBalancePct < -10 || stockHealth === "watch") return {signal:"yellow",label:"🟡 持續觀察",note:"目前仍有壓力，需追蹤後續價格與結構變化"};return {signal:"green",label:"🟢 可續抱",note:"結構與目前狀態仍可接受"};}
function toDate(value){const d=new Date(value);return Number.isNaN(d.getTime())?null:d;}
function formatDate(value){const d=toDate(value);return d?d.toISOString().slice(0,10):"";}
function addDays(dateValue,days){const d=toDate(dateValue);if(!d)return null;const x=new Date(d);x.setDate(x.getDate()+days);return x;}
function addMonthsSafe(dateValue,months){const d=toDate(dateValue);if(!d)return null;const x=new Date(d),originalDay=x.getDate();x.setMonth(x.getMonth()+months);if(x.getDate()<originalDay)x.setDate(0);return x;}
function daysBetween(a,b){const da=toDate(a),db=toDate(b);if(!da||!db)return 0;return Math.max(0,Math.floor((db-da)/(1000*60*60*24)));}
function getFCNId(fcn){return String(fcn.fcn_id||"").trim();}
function getEntryTime(fcn){return fcn.entry_time||fcn.created_time||fcn.date||"";}
function getMaturityDate(fcn){if(fcn.exit_time){const d=toDate(fcn.exit_time);if(d)return d;}const entry=getEntryTime(fcn),tenor=toNumber(fcn.tenor,0);return entry&&tenor?addMonthsSafe(entry,tenor):null;}
function readLocalJson(key){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):{};}catch{return {};}}
function writeLocalJson(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
function readEarlyExitState(){return readLocalJson(M2_EARLY_EXIT_STATE_KEY);}
function writeEarlyExitState(state){writeLocalJson(M2_EARLY_EXIT_STATE_KEY,state);}
function readKnockInState(){return readLocalJson(M2_KNOCKIN_STATE_KEY);}
function writeKnockInState(state){writeLocalJson(M2_KNOCKIN_STATE_KEY,state);}
function calcEarlyExit(fcn,marketRuntime={},state={}){const fcnId=getFCNId(fcn),basket=Array.isArray(fcn.basket)?fcn.basket:[],entryTime=getEntryTime(fcn),checkStartDate=addDays(entryTime,37),maturityDate=getMaturityDate(fcn),now=new Date(),eligible=!!checkStartDate&&now>=checkStartDate,beforeMaturity=maturityDate?now<maturityDate:true,fcnRecord=fcn.early_exit_record||{};if(!state[fcnId])state[fcnId]={};const legacy=state[fcnId],mergedRecord={};const stocks=basket.map(symbol=>{const rec=fcnRecord[symbol]||{},old=legacy[symbol]||{},prevHit=rec.hit||old.met||false,prevDate=rec.first_hit_time||old.remark_date||"",entry=Number(fcn.entry_prices?.[symbol]),price=Number(marketRuntime?.[symbol]?.price_now),autocallPct=toNumber(fcn.autocall,100),autocallPrice=entry*autocallPct/100,hitToday=eligible&&beforeMaturity&&Number.isFinite(entry)&&Number.isFinite(price)&&price>=autocallPrice,hit=prevHit||hitToday,date=prevDate||(hitToday?formatDate(now):"");mergedRecord[symbol]={hit,first_hit_time:date};legacy[symbol]={met:hit,remark_date:date};return{symbol,met:hit,remark_date:date};});const total=basket.length,hitCount=stocks.filter(s=>s.met).length,ready=eligible&&beforeMaturity&&hitCount===total;return{early_exit_record:mergedRecord,early_exit_stocks:stocks,early_exit_eligible:eligible,early_exit_ready:ready,early_exit_remark_count:hitCount,early_exit_total_count:total,early_exit_check_start_date:formatDate(checkStartDate)};}
function calcInterestAndPL(fcn,stock){const investAmt=toNumber(fcn.amt,0),annualRate=toNumber(fcn.rate,0)/100,tenorMonths=toNumber(fcn.tenor,0),entryPrice=toNumber(stock.entry_price,0),priceNow=toNumber(stock.price_now,0),strikePct=toNumber(fcn.strike,0)/100;if(!investAmt||!annualRate||!tenorMonths||!entryPrice||!strikePct)return{strike_price:0,snapshot_loss_amt:0,snapshot_loss_pct:0,snapshot_interest_amt:0,snapshot_interest_pct:0,snapshot_balance_amt:0,snapshot_balance_pct:0,end_loss_amt:0,end_loss_pct:0,end_interest_amt:0,end_interest_pct:0,end_balance_amt:0,end_balance_pct:0,months_held_full:0};const strikePrice=entryPrice*strikePct,lossPct=Math.min(strikePrice?((priceNow-strikePrice)/strikePrice)*100:0,0),lossAmt=investAmt*lossPct/100,monthsHeld=fullMonthsHeld(fcn.entry_time||fcn.created_time),snapshotInterestAmt=investAmt*(annualRate/12)*monthsHeld,snapshotInterestPct=investAmt?snapshotInterestAmt/investAmt*100:0,snapshotBalanceAmt=lossAmt+snapshotInterestAmt,snapshotBalancePct=investAmt?snapshotBalanceAmt/investAmt*100:0,endInterestAmt=investAmt*annualRate*(tenorMonths/12),endInterestPct=investAmt?endInterestAmt/investAmt*100:0,endBalanceAmt=lossAmt+endInterestAmt,endBalancePct=investAmt?endBalanceAmt/investAmt*100:0;return{strike_price:round(strikePrice),snapshot_loss_amt:round(lossAmt),snapshot_loss_pct:round(lossPct),snapshot_interest_amt:round(snapshotInterestAmt),snapshot_interest_pct:round(snapshotInterestPct),snapshot_balance_amt:round(snapshotBalanceAmt),snapshot_balance_pct:round(snapshotBalancePct),end_loss_amt:round(lossAmt),end_loss_pct:round(lossPct),end_interest_amt:round(endInterestAmt),end_interest_pct:round(endInterestPct),end_balance_amt:round(endBalanceAmt),end_balance_pct:round(endBalancePct),months_held_full:monthsHeld};}
function calcStockHealth(symbol,fcn,market,poolMap={}){const runtime=market?.[symbol]||{},entry_price=toNumber(fcn.entry_prices?.[symbol]),price_now=toNumber(runtime.price_now);if(!entry_price||!price_now)return null;const ki_pct=toNumber(fcn.ki),strike_pct=toNumber(fcn.strike),ki_price=entry_price*ki_pct/100,strike_price_raw=entry_price*strike_pct/100,dist_to_ki_pct=ki_price?((price_now-ki_price)/ki_price)*100:0,dist_to_strike_pct=strike_price_raw?((price_now-strike_price_raw)/strike_price_raw)*100:0;let stock_health="healthy";if(price_now<ki_price)stock_health="danger";else if(price_now<strike_price_raw)stock_health="watch";const pnl=calcInterestAndPL(fcn,{entry_price,price_now}),decision=getDecisionSignal(pnl.snapshot_balance_pct,pnl.end_balance_pct,stock_health);return{symbol,entry_price,price_now,ki_pct,strike_pct,ki_price:round(ki_price),strike_price:pnl.strike_price,dist_to_ki_pct:round(dist_to_ki_pct),dist_to_strike_pct:round(dist_to_strike_pct),stock_health,category:poolMap[symbol]?.category??"",sector:poolMap[symbol]?.sector??"",subsector:poolMap[symbol]?.subsector??"",pure_stock:runtime.pure_stock??null,snapshot_score:runtime.snapshot_score??null,event_stock:runtime.event_stock??null,trend:runtime.trend??"",trend_note:runtime.trend_note??"",ret_1w:runtime.ret_1w??runtime.chg_1w??null,ret_1m:runtime.ret_1m??runtime.chg_1m??null,ret_3m:runtime.ret_3m??runtime.chg_3m??null,ret_6m:runtime.ret_6m??runtime.chg_6m??null,ret_12m:runtime.ret_12m??runtime.chg_12m??null,decision_signal:decision.signal,decision_label:decision.label,decision_note:decision.note,...pnl};}
function sortStocks(stocks){const order={danger:0,watch:1,healthy:2};return[...stocks].sort((a,b)=>order[a.stock_health]!==order[b.stock_health]?order[a.stock_health]-order[b.stock_health]:a.dist_to_ki_pct-b.dist_to_ki_pct);}
function updateKnockInState(fcn,stocks,knockInState){const fcnId=getFCNId(fcn);if(fcn.eki)return{has_knock_in:false,knock_in_date:"",has_ki_breach:false,first_ki_breach_time:""};if(!knockInState[fcnId])knockInState[fcnId]={};const bucket=knockInState[fcnId],today=formatDate(new Date()),prevHas=fcn.has_ki_breach||bucket.has_knock_in||false,prevDate=fcn.first_ki_breach_time||bucket.knock_in_date||"",breachToday=stocks.some(s=>Number(s.price_now)<Number(s.ki_price)),has=prevHas||breachToday,date=prevDate||(breachToday?today:"");bucket.has_knock_in=has;bucket.knock_in_date=date;return{has_knock_in:has,knock_in_date:date,has_ki_breach:has,first_ki_breach_time:date};}
function calcMaturityZone(fcn,stocks,earlyExit){const now=new Date(),maturityDate=getMaturityDate(fcn),days_to_maturity=maturityDate?daysBetween(now,maturityDate):9999,in_maturity_window=days_to_maturity<=10,isEKI=!!fcn.eki,all_above_strike=stocks.length>0&&stocks.every(s=>toNumber(s.price_now)>=toNumber(s.strike_price)),any_below_strike=stocks.some(s=>toNumber(s.price_now)<toNumber(s.strike_price)),all_above_ki=stocks.length>0&&stocks.every(s=>toNumber(s.price_now)>=toNumber(s.ki_price)),any_below_ki=stocks.some(s=>toNumber(s.price_now)<toNumber(s.ki_price));let maturity_safe=false,maturity_risk=false,maturity_label="",maturity_color="",maturity_note="";if(earlyExit.early_exit_ready){maturity_label="提早出場";maturity_color="blue";maturity_note="已滿足提早出場條件";}else if(in_maturity_window){if(isEKI&&all_above_ki){maturity_safe=true;maturity_label="滿期安全";maturity_color="green";maturity_note="EKI 到期判斷：全部標的已回到 KI 以上";}else if(isEKI&&any_below_ki){maturity_risk=true;maturity_label="接股可能";maturity_color="red";maturity_note="EKI 到期判斷：仍有標的低於 KI，存在接股風險";}else if(!isEKI&&all_above_strike){maturity_safe=true;maturity_label="滿期安全";maturity_color="green";maturity_note="AKI / DACN 到期判斷：全部標的已回到 Strike 以上";}else if(!isEKI&&any_below_strike){maturity_risk=true;maturity_label="接股可能";maturity_color="red";maturity_note="AKI / DACN 到期判斷：仍有標的低於 Strike，存在接股風險";}}return{days_to_maturity,in_maturity_window,all_above_strike,any_below_strike,all_above_ki,any_below_ki,maturity_safe,maturity_risk,maturity_label,maturity_color,maturity_note};}
function calcFCN(fcn,market,poolMap={},earlyExitState={},knockInState={}){const stocks=(fcn.basket||[]).map(symbol=>calcStockHealth(symbol,fcn,market,poolMap)).filter(Boolean);if(!stocks.length)return null;const sorted=sortStocks(stocks),danger_count=sorted.filter(s=>s.stock_health==="danger").length,watch_count=sorted.filter(s=>s.stock_health==="watch").length,healthy_count=sorted.filter(s=>s.stock_health==="healthy").length,earlyExit=calcEarlyExit(fcn,market,earlyExitState),knockInInfo=updateKnockInState(fcn,sorted,knockInState),maturity=calcMaturityZone(fcn,sorted,earlyExit);let fcn_health="healthy";if(!fcn.eki&&knockInInfo.has_knock_in){fcn_health=sorted.some(s=>toNumber(s.price_now)<toNumber(s.strike_price))?"danger":"watch";}else if(danger_count>0)fcn_health="danger";else if(watch_count>0)fcn_health="watch";const worst=sorted[0],decision=getDecisionSignal(worst.snapshot_balance_pct,worst.end_balance_pct,fcn_health),earlyExitStockMap={};(earlyExit.early_exit_stocks||[]).forEach(s=>earlyExitStockMap[s.symbol]=s);const mergedStocks=sorted.map(s=>({...s,early_exit_met:!!earlyExitStockMap[s.symbol]?.met,early_exit_remark_date:earlyExitStockMap[s.symbol]?.remark_date||""})),earlyExitLabel=earlyExit.early_exit_ready?"⏩ 可提早出場":earlyExit.early_exit_eligible?`⏳ 提早出場追蹤中 ${earlyExit.early_exit_remark_count}/${earlyExit.early_exit_total_count}`:"尚未進入提早出場觀察期";return{...fcn,fcn_health,worst_of:worst.symbol,danger_count,watch_count,healthy_count,worst_dist_to_ki_pct:worst.dist_to_ki_pct,worst_dist_to_strike_pct:worst.dist_to_strike_pct,snapshot_loss_amt:worst.snapshot_loss_amt,snapshot_loss_pct:worst.snapshot_loss_pct,snapshot_interest_amt:worst.snapshot_interest_amt,snapshot_interest_pct:worst.snapshot_interest_pct,snapshot_balance_amt:worst.snapshot_balance_amt,snapshot_balance_pct:worst.snapshot_balance_pct,end_loss_amt:worst.end_loss_amt,end_loss_pct:worst.end_loss_pct,end_interest_amt:worst.end_interest_amt,end_interest_pct:worst.end_interest_pct,end_balance_amt:worst.end_balance_amt,end_balance_pct:worst.end_balance_pct,months_held_full:worst.months_held_full,decision_signal:decision.signal,decision_label:decision.label,decision_note:decision.note,...earlyExit,early_exit_label:earlyExitLabel,...knockInInfo,maturity,stocks:mergedStocks};}
function buildStockAggregation(fcns){const map={};fcns.forEach(f=>(f.stocks||[]).forEach(s=>{if(!map[s.symbol])map[s.symbol]={symbol:s.symbol,category:s.category,sector:s.sector,subsector:s.subsector,pure_stock:s.pure_stock,event_stock:s.event_stock,count:0,amt:0,danger:0,watch:0,healthy:0,fcns:[],details:[]};const obj=map[s.symbol];obj.count++;obj.amt+=toNumber(f.amt);obj.fcns.push(f.fcn_id);obj.details.push({fcn_id:f.fcn_id,fcn:f,stock:s});if(s.stock_health==="danger")obj.danger++;else if(s.stock_health==="watch")obj.watch++;else obj.healthy++;}));return Object.values(map).sort((a,b)=>b.amt-a.amt);}
export function runM2HealthEngine({fcnPool=[],marketRuntime={},pool30=[]}){const poolMap={};pool30.forEach(p=>poolMap[p.symbol]=p);const earlyExitState=readEarlyExitState(),knockInState=readKnockInState(),active=fcnPool.filter(f=>f.status==="active"),fcns=active.map(f=>calcFCN(f,marketRuntime,poolMap,earlyExitState,knockInState)).filter(Boolean);writeEarlyExitState(earlyExitState);writeKnockInState(knockInState);const maturity_zone=fcns.filter(f=>f.early_exit_ready||f.maturity?.in_maturity_window),maturity_exit=maturity_zone.filter(f=>f.early_exit_ready),maturity_safe=maturity_zone.filter(f=>!f.early_exit_ready&&f.maturity?.maturity_safe),maturity_risk=maturity_zone.filter(f=>!f.early_exit_ready&&f.maturity?.maturity_risk),nonMaturityFCNs=fcns.filter(f=>!(f.early_exit_ready||f.maturity?.in_maturity_window)),danger=nonMaturityFCNs.filter(f=>f.fcn_health==="danger"),watch=nonMaturityFCNs.filter(f=>f.fcn_health==="watch"),healthy=nonMaturityFCNs.filter(f=>f.fcn_health==="healthy"),stockMap=buildStockAggregation(fcns);return{fcns,maturity_zone,maturity_exit,maturity_safe,maturity_risk,danger,watch,healthy,stockMap,total:fcns.length,total_amt:round(fcns.reduce((s,f)=>s+toNumber(f.amt),0))};}
export function buildFCNMeta(f){return `<div style="font-size:13px; color:#444; margin-bottom:10px; line-height:1.6;"><b>📦 結構：</b>${f.tenor??"-"}M｜${f.rate??"-"}%｜KI ${f.ki??"-"}%｜Strike ${f.strike??"-"}%｜Autocall ${f.autocall??"-"}%｜${f.eki?"🟢 EKI":"⚪ AKI / DACN"}<br>建立：${f.created_time||"-"}｜進場：${f.entry_time||"-"}</div>`;}
export function limitDisplay(arr,type,showAllHealthy=false){return type==="healthy"&&!showAllHealthy?arr.slice(0,5):arr;}
