// ============================================================
// M8 Batch Decision UI v0.6.0
// Path: js/mm/m2/m8_batch_decision_ui.js
// Purpose: Turn B-zone market template data into a decision board.
// ============================================================
(function(){
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'-';
const pct=(v,d=2)=>Number.isFinite(Number(v))?`${fmt(v,d)}%`:'-';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function css(){return `<style>.bdui{display:grid;gap:14px}.bdui-hero{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:12px}.bdui-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:14px;box-shadow:0 2px 8px rgba(15,23,42,.04)}.bdui-card h3{margin:0 0 8px;font-size:17px}.bdui-big{font-size:26px;font-weight:950;color:#0f172a}.bdui-sub{font-size:13px;color:#64748b;line-height:1.55}.bdui-good{border-left:5px solid #0f766e}.bdui-hot{border-left:5px solid #f97316}.bdui-bad{border-left:5px solid #dc2626}.bdui-gray{border-left:5px solid #94a3b8}.bdui-heat{display:grid;grid-template-columns:repeat(4,minmax(160px,1fr));gap:10px}.bdui-template{border:1px solid #e5e7eb;border-radius:16px;background:#fff;padding:12px;cursor:pointer}.bdui-template.active{outline:3px solid #bfdbfe;background:#f8fbff}.bdui-template b{display:block;font-size:14px;word-break:break-word}.bdui-chip{display:inline-block;border-radius:999px;padding:4px 8px;margin-top:6px;font-size:12px;font-weight:900;background:#f1f5f9;color:#334155}.bdui-chip.update{background:#ffedd5;color:#9a3412}.bdui-chip.watch{background:#fef9c3;color:#854d0e}.bdui-chip.promote{background:#dcfce7;color:#166534}.bdui-chip.recalibrate{background:#fee2e2;color:#991b1b}.bdui-small-grid{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:10px}.bdui-small{border:1px solid #e5e7eb;border-radius:16px;background:#fff;padding:12px}.bdui-small-title{font-size:15px;font-weight:950;word-break:break-word}.bdui-kv{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.bdui-kv div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:8px}.bdui-kv label{display:block;font-size:11px;color:#64748b;font-weight:900}.bdui-kv strong{display:block;font-size:16px;color:#0f172a}.bdui-comment{border:1px solid #dbeafe;background:#f8fbff;border-radius:12px;padding:10px;font-size:13px;line-height:1.6;color:#334155}.bdui-details summary{font-weight:900;cursor:pointer}.bdui-table{width:100%;border-collapse:collapse;font-size:12px}.bdui-table th,.bdui-table td{border-bottom:1px solid #e5e7eb;padding:7px;text-align:left}.bdui-table th{background:#f8fafc}@media(max-width:1100px){.bdui-hero,.bdui-heat,.bdui-small-grid{grid-template-columns:1fr}}</style>`}
function actionFor(count,gap){count=n(count,0);gap=n(gap,0);if(count>=5&&Math.abs(gap)<=1)return{key:'promote',label:'Promote',text:'樣本足且貼近市場，可作主力小模板。'};if(count>=3&&Math.abs(gap)>3)return{key:'recalibrate',label:'Recalibrate',text:'樣本足但偏離大，應進入校正清單。'};if(count>=3)return{key:'update',label:'Update Candidate',text:'樣本達標，可列入 surface 更新候選。'};return{key:'watch',label:'Watch',text:'樣本不足，先觀察，不急著寫 surface。'} }
function templateState(t){const gap=n(t.gap_final_pct,0),count=n(t.count,0);if(count<3)return{cls:'bdui-gray',text:'樣本不足'};if(gap>3)return{cls:'bdui-hot',text:'市場偏甜'};if(gap<-3)return{cls:'bdui-bad',text:'市場偏貴'};return{cls:'bdui-good',text:'接近市場'}}
function renderTemplate(t,i,active){const st=templateState(t);const a=actionFor(t.count,t.gap_final_pct);return `<div class="bdui-template ${active?'active':''}" data-bdui-template="${i}"><b>${esc(t.template)}</b><div class="bdui-sub">${t.count} rows｜Mkt ${pct(t.market,2)}｜Final ${pct(t.final_fair,2)}</div><span class="bdui-chip ${a.key}">${a.label}</span><div class="bdui-sub">Gap ${pct(t.gap_final_pct,2)}｜${st.text}</div></div>`}
function renderSmallCard(s){const a=actionFor(s.count,s.gap_after_pct);return `<div class="bdui-small"><div class="bdui-small-title">${esc(s.key)}</div><span class="bdui-chip ${a.key}">${a.label}</span><div class="bdui-kv"><div><label>Rows</label><strong>${s.count||0}</strong></div><div><label>Market</label><strong>${pct(s.market,2)}</strong></div><div><label>Final AVG</label><strong>${pct(s.final_fair,2)}</strong></div><div><label>New Fair</label><strong>${pct(s.new_fair,2)}</strong></div><div><label>Gap</label><strong>${pct(s.gap_after_pct,2)}</strong></div><div><label>Type</label><strong>${esc(s.group_type||'-')}</strong></div></div><div class="bdui-comment">${a.text}</div><details class="bdui-details"><summary>Included rows</summary>${renderRows(s.included_rows||[])}</details></div>`}
function renderRows(rows){return `<table class="bdui-table"><thead><tr><th>FCN</th><th>Basket</th><th>Market</th><th>Final</th><th>Strike/KI</th><th>Tenor</th></tr></thead><tbody>${rows.slice(0,20).map(r=>`<tr><td>${esc(r.fcn_id)}</td><td>${esc(r.basket)}</td><td>${pct(r.market_coupon,2)}</td><td>${pct(r.final_fair,2)}</td><td>${fmt(r.strike,1)} / ${fmt(r.ki,1)}</td><td>${r.tenor||'-'}</td></tr>`).join('')}</tbody></table>`}
function executive(summary){const total=summary.reduce((s,t)=>s+n(t.count,0),0);const avgGap=summary.length?summary.reduce((s,t)=>s+n(t.gap_final_pct,0)*n(t.count,1),0)/Math.max(1,total):0;const top=[...summary].sort((a,b)=>Math.abs(n(b.gap_final_pct,0))*n(b.count,0)-Math.abs(n(a.gap_final_pct,0))*n(a.count,0)).slice(0,3);const state=avgGap>2?'整體偏甜':avgGap<-2?'整體偏貴':'整體接近市場';const need=top.some(t=>n(t.count,0)>=3&&Math.abs(n(t.gap_final_pct,0))>3)?'需要更新 / 校正 surface':'暫以觀察為主';return{total,avgGap,top,state,need}}
function renderBoard(workspace={},selectedIndex=0){const summary=workspace.templateSummary||[];const radar=workspace.radar||[];const ex=executive(summary);const t=summary[selectedIndex]||summary[0]||null;return `${css()}<div class="bdui"><div class="bdui-hero"><div class="bdui-card bdui-good"><h3>B0. Executive Summary</h3><div class="bdui-big">${esc(ex.state)}</div><div class="bdui-sub">Rows ${ex.total}｜Weighted Gap ${pct(ex.avgGap,2)}｜${esc(ex.need)}</div></div><div class="bdui-card bdui-hot"><h3>Top Watch Templates</h3><div class="bdui-sub">${ex.top.map(x=>`${esc(x.template)}：${pct(x.gap_final_pct,2)} / ${x.count} rows`).join('<br>')||'-'}</div></div><div class="bdui-card bdui-gray"><h3>Surface Action</h3><div class="bdui-big">${radar.filter(r=>r.coverage==='candidate').length}</div><div class="bdui-sub">small-template candidates｜明細在下方 Action Cards</div></div></div><div class="bdui-card"><h3>B1. Template Heatmap</h3><div class="bdui-heat">${summary.map((x,i)=>renderTemplate(x,i,i===selectedIndex)).join('')}</div></div>${t?`<div class="bdui-card"><h3>B2. Small Template Action Cards｜${esc(t.template)}</h3><div class="bdui-small-grid">${(t.subtemplates||[]).map(renderSmallCard).join('')||'<div class="bdui-sub">No subtemplates.</div>'}</div></div>`:''}</div>`}
window.renderM8BatchDecisionBoard=renderBoard;
})();
